app/package/urls.py
from django.conf.urls import url
from django.views.generic.dates import ArchiveIndexView

from package.models import Project
from package.views import (
    add_example,
    add_package,
    ajax_package_list,
    edit_package,
    edit_example,
    update_package,
    usage,
    package_list,
    package_detail,
    post_data,
    edit_documentation,
    github_webhook,
    edit_images,
    project_approval,
    publish_project,
)
from timeline.views import (
    edit_timeline,
    add_ruleset,
    edit_ruleset,
    delete_ruleset,
)


urlpatterns = [

    url(
        regex=r"^$",
        view=package_list,
        name="packages",
    ),

    url(
        regex=r"^latest/$",
        view=ArchiveIndexView.as_view(
                        queryset=Project.objects.filter().select_related(),
                        paginate_by=50,
                        date_field="created"
        ),
        name="latest_packages",
    ),
    url(
        regex="^add/$",
        view=add_package,
        name="add_package",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/edit/$",
        view=edit_package,
        name="edit_package",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/timeline/edit/$",
        view=edit_timeline,
        name="edit_timeline",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/timeline/ruleset/add/$",
        view=add_ruleset,
        name="add_ruleset",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/timeline/ruleset/(?P<ruleset_id>[\d]+)/edit/$",
        view=edit_ruleset,
        name="edit_ruleset",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/timeline/ruleset/(?P<ruleset_id>[\d]+)/delete/$",
        view=delete_ruleset,
        name="delete_ruleset",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/images/edit/$",
        view=edit_images,
        name="edit_images",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/fetch-data/$",
        view=update_package,
        name="fetch_package_data",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/approval/(?P<action>request|cancel)/$",
        view=project_approval,
        name="project_approval",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/publish/$",
        view=publish_project,
        name="publish_project",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/post-data/$",
        view=post_data,
        name="post_package_data",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/example/add/$",
        view=add_example,
        name="add_example",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/example/(?P<id>\d+)/edit/$",
        view=edit_example,
        name="edit_example",
    ),

    url(
        regex="^p/(?P<slug>[-\w]+)/$",
        view=package_detail,
        name="package",
    ),

    url(
        regex="^ajax_package_list/$",
        view=ajax_package_list,
        name="ajax_package_list",
    ),

    url(
        regex="^usage/(?P<slug>[-\w]+)/(?P<action>add|remove)/$",
        view=usage,
        name="usage",
    ),

    url(
        regex="^(?P<slug>[-\w]+)/document/$",
        view=edit_documentation,
        name="edit_documentation",
    ),
    url(
        regex="^github-webhook/$",
        view=github_webhook,
        name="github_webhook"
    ),
]

app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.urls.base import reverse_lazy
from django.views.generic.base import TemplateView, RedirectView

from django.contrib import admin

from core.views import StaticPageView
from package.models import TeamMembership
from profiles.views import profile_detail
from social_auth_local.views import require_email, validation_sent, merging_accounts

admin.autodiscover()

from apiv4.viewsets import router
from core.apiv1 import apiv1_gone
from homepage.views import homepage, error_404_view, error_500_view, health_check_view, SitemapView
from package.views import category, python3_list
from django.contrib.auth.views import logout as contrib_logout_view

urlpatterns = [

    url(r'^login/\{\{item\.absolute_url\}\}/', RedirectView.as_view(url="/login/github/")),
    url('^auth/', include('social_django.urls', namespace='social')),
    url(r'^auth/email/$', require_email, name='require_email'),
    url(r'^auth/email-sent/', validation_sent, name='validation_sent'),
    url(r'^auth/merging_accounts/', merging_accounts, name='merging_accounts'),
    # url('', include('social_auth.urls')),
    url(r"^$", homepage, name="home"),
    url(r"^health_check/$", health_check_view, name="health_check"),
    url(settings.ADMIN_URL_BASE, include(admin.site.urls)),
    url(r"^profiles/", include("profiles.urls")),
    url(r"^@(?P<hive_account>[-\.\w]+)", lambda request, hive_account: redirect('hive_profile_detail', hive_account, permanent=True)),
    url(r"^projects/", include("package.urls")),
    url(r"^grids/", include("grid.urls")),
    url(r"^feeds/", include("feeds.urls")),
    url(r'^newsletter/', include('newsletter.urls')),

    url(r"^categories/(?P<slug>[-\w]+)/$", category, name="category"),
    url(r"^categories/$", homepage, name="categories"),
    url(r"^python3/$", python3_list, name="py3_compat"),

    url(regex=r'^login/$', view=TemplateView.as_view(template_name='pages/login.html'), name='login',),
    url(r'^logout/$', contrib_logout_view, {'next_page': '/'}, 'logout',),

    # static pages
    url(r"^about/$", TemplateView.as_view(template_name='pages/faq.html'), name="about"),
    url(r"^terms/$", TemplateView.as_view(template_name='pages/terms.html'), name="terms"),
    url(r"^faq/$", TemplateView.as_view(template_name='pages/faq.html'), name="faq"),
    url(r"^syndication/$", TemplateView.as_view(template_name='pages/syndication.html'), name="syndication"),
    url(
        r"^contribute/$",
        StaticPageView.as_view(
            template_name='pages/contribute.html',
            context={
                "membership_in_hiveprojects": TeamMembership.objects.filter(project__name="Hive Projects"),
            },
        ),

        name="contribute"
    ),
    url(r"^help/$", TemplateView.as_view(template_name='pages/help.html'), name="help"),
    url(r"^sitemap\.xml$", SitemapView.as_view(), name="sitemap"),

    # new apps
    url(r"^search/", include("searchv2.urls")),

    # apiv2
    # url(r'^api/v2/', include('core.apiv2', namespace="apiv2")),

    # apiv3
    url(r'^api/v3/', include('apiv3.urls', namespace="apiv3")),

    # apiv4
    url(r'^api/v4/', include(router.urls, namespace='apiv4')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(
        regex=r"^api/v1/.*$",
        view=apiv1_gone,
        name="apiv1_gone",
    ),

    # url(r'^api/v1/', include('core.apiv1', namespace="apitest")),

    # reports
    # url(r'^reports/', include('reports.urls', namespace='reports')),

    url(r"^error/$", lambda request: 1/0),  # should trigger sentry
    url(r"^500/$", error_500_view),
    url(r"^404/$", error_404_view),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'homepage.views.error_500_view'
handler404 = 'homepage.views.error_404_view'
# handler403 = ''
# handler400 = ''

app/package/models.py
from datetime import datetime, timedelta
import json
import re
import os
import time

from django.core.cache import cache
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models.query import QuerySet
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.utils.safestring import mark_safe

from distutils.version import LooseVersion as versioner
import requests

from core.fields import SizeAndContentTypeRestrictedImageField
from core.utils import STATUS_CHOICES, status_choices_switch
from core.models import BaseModel
from package.repos import get_repo_for_repo_url
from package.signals import signal_fetch_latest_metadata
from package.utils import get_version, get_pypi_version, normalize_license
from profiles.models import Profile, Account
from simple_history.models import HistoricalRecords

repo_url_help_text = settings.PACKAGINATOR_HELP_TEXT['REPO_URL']
pypi_url_help_text = settings.PACKAGINATOR_HELP_TEXT['PYPI_URL']


class NoPyPiVersionFound(Exception):
    pass


class Category(BaseModel):

    title = models.CharField(_("Title"), max_length=50)
    slug = models.SlugField(_("slug"))
    description = models.TextField(_("description"), blank=True)
    title_plural = models.CharField(_("Title Plural"), max_length=50, blank=True)
    show_github = models.BooleanField(_("Show Github stats"), default=False)

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ("category", [self.slug])


class ProjectQuerySet(QuerySet):
    def published(self):
        return self.filter(is_published=True)

    def drafts(self):
        return self.filter(is_published=False)


class Project(BaseModel):
    NONE_STATUS = ""
    UNKNOWN = "UNKNOWN"
    LIVE__RELEASED = "LIVE_RELEASED"
    WORKING_PROTOTYPE__BETA = "WORKINGPROTOTYPE_BETA"
    DEMO__ALPHA = "DEMO_ALPHA"
    CONCEPT = "CONCEPT"
    ABANDONED__BROKEN = "ABANDONED_BROKEN"
    OUT_OF_DATE__RETIRED = "OUTOFDATE_RETIRED"

    STATUSES = [
        {
            'id': NONE_STATUS,
            'name': '----',
            'description': '',
        },
        {
            'id': UNKNOWN,
            'name': 'Unknown',
            'description': 'Unknown project status',
        },
        {
            'id': LIVE__RELEASED,
            'name': 'Live/Released',
            'description': 'Project is ready to use',
        },
        {
            'id': WORKING_PROTOTYPE__BETA,
            'name': 'Working Prototype/Beta',
            'description': 'Project is working however, it still can contain some bugs',
        },
        {
            'id': DEMO__ALPHA,
            'name': 'Demo/Alpha',
            'description': 'Project can be used by people which are not afraid of bugs and has very high pain threshold',
        },
        {
            'id': CONCEPT,
            'name': 'Concept',
            'description': 'Project which pretends to be a working product',
        },
        {
            'id': ABANDONED__BROKEN,
            'name': 'Abandoned/Broken',
            'description': 'Project is no longer available or it is completely broken',
        },
        {
            'id': OUT_OF_DATE__RETIRED,
            'name': 'Out of Date/Retired',
            'description': 'Project is no longer needed, because of changes in ecosystem',
        },

    ]

    STATUS_CHOICES = [(status["id"], status["name"]) for status in STATUSES]

    name = models.CharField(_("Name"), max_length=100, unique=True)
    url = models.URLField(_("Project URL"), blank=True, null=True, unique=True)
    status = models.CharField(
        _("Status"),
        max_length=100,
        choices=STATUS_CHOICES,
        default=NONE_STATUS,
        help_text=mark_safe(
            "<ul>{}</ul>".format(
                "".join([
                    "<li><strong>{name}</strong> - {description}</li>".format(**status)
                    for status in STATUSES
                    if status["id"] not in ["", "UNKNOWN"]
                ])
            )
        )
    )
    description = models.TextField(_("Description"), blank=True, null=True, default="")
    announcement_post = models.URLField(_("Announcement Post URL"), blank=True, null=True, help_text="Link to place, where project was announced for the first time")
    contact_url = models.URLField(_("Contact URL"), blank=True, null=True, default=None)
    slug = models.SlugField(_("Slug"), help_text="Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens. Values will be converted to lowercase.", unique=True)
    category = models.ForeignKey(Category, verbose_name="Category")
    repo_description = models.TextField(_("Repo Description"), blank=True)
    repo_url = models.URLField(_("Repository URL"), help_text=repo_url_help_text, blank=True, null=True, unique=True)
    repo_watchers = models.IntegerField(_("Stars"), default=0)
    repo_forks = models.IntegerField(_("repo forks"), default=0)
    pypi_url = models.CharField(_("PyPI slug"), max_length=255, help_text=pypi_url_help_text, blank=True, default='')
    pypi_downloads = models.IntegerField(_("Pypi downloads"), default=0)
    participants = models.TextField(_("Participants"),
                        help_text="List of collaborats/participants on the project", blank=True)
    team_members = models.ManyToManyField(Account, through='TeamMembership', blank=True, related_name="team_member_of", through_fields=("project", "account"))
    contributors = models.ManyToManyField(Account, blank=True, related_name="contribiuted_to")
    usage = models.ManyToManyField(User, blank=True)
    draft_added_by = models.ForeignKey(User, blank=True, null=True, related_name="drafted_projects", on_delete=models.SET_NULL)
    is_awaiting_approval = models.BooleanField(blank=True, null=None, default=False)
    is_published = models.BooleanField(blank=True, null=None, default=False)
    publication_time = models.DateTimeField(_("Publication time"), blank=True, null=True, default=None)
    approval_request_datetime = models.DateTimeField(blank=True, null=True, default=None)
    approvers = models.ManyToManyField(User, blank=True, related_name='approved_projects')
    last_modified_by = models.ForeignKey(User, blank=True, null=True, related_name="modifier", on_delete=models.SET_NULL)
    last_fetched = models.DateTimeField(blank=True, null=True, default=timezone.now)
    documentation_url = models.URLField(_("Documentation URL"), blank=True, null=True, default="")


    commit_list = models.TextField(_("Commit List"), blank=True)
    main_img = models.ForeignKey('ProjectImage', null=True, blank=True, related_name='main_img_proj')

    history = HistoricalRecords()

    objects = ProjectQuerySet.as_manager()

    @property
    def img(self):
        if self.main_img:
            return self.main_img.img
        elif self.images.count():
            return self.images.order_by("id").first().img
        else:
            return None

    @property
    def is_draft(self):
        return not self.is_published

    def can_be_published(self, publisher):
        return publisher.is_staff or publisher.profile.is_trusted

    def publish(self, publisher):
        if not self.can_be_published(publisher):
            raise PermissionError()

        self.is_published = True
        self.is_awaiting_approval = False
        self.approvers.add(publisher)
        self.publication_time = datetime.now()
        self.save()


    @property
    def pypi_name(self):
        """ return the pypi name of a package"""

        if not self.pypi_url.strip():
            return ""

        name = self.pypi_url.replace("http://pypi.python.org/pypi/", "")
        if "/" in name:
            return name[:name.index("/")]
        return name

    def last_updated(self):
        cache_name = self.cache_namer(self.last_updated)
        last_commit = cache.get(cache_name)
        if last_commit is not None:
            return last_commit
        try:
            last_commit = self.commit_set.latest('commit_date').commit_date
            if last_commit:
                cache.set(cache_name, last_commit)
                return last_commit
        except ObjectDoesNotExist:
            last_commit = None

        return last_commit

    @property
    def repo(self):
        return get_repo_for_repo_url(self.repo_url)

    @property
    def active_examples(self):
        return self.packageexample_set.filter(active=True)

    @property
    def license_latest(self):
        try:
            return self.version_set.latest().license
        except Version.DoesNotExist:
            return "UNKNOWN"

    def grids(self):

        return [x.grid for x in self.gridpackage_set.all()]

    def repo_name(self):
        return re.sub(self.repo.url_regex, '', self.repo_url)

    def repo_info(self):
        return dict(
            username=self.repo_name().split('/')[0],
            repo_name=self.repo_name().split('/')[1],
        )

    def participant_list(self):

        return self.participants.split(',')

    def get_usage_count(self):
        return self.usage.count()

    def commits_over_52(self):
        cache_name = self.cache_namer(self.commits_over_52)
        value = cache.get(cache_name)
        if value is not None:
            return value
        now = datetime.now()
        commits = self.commit_set.filter(
            commit_date__gt=now - timedelta(weeks=52),
        ).values_list('commit_date', flat=True)

        weeks = [0] * 52
        for cdate in commits:
            age_weeks = (now - cdate).days // 7
            if age_weeks < 52:
                weeks[age_weeks] += 1

        value = ','.join(map(str, reversed(weeks)))
        cache.set(cache_name, value)
        return value

app/templates/package/add_example.html
{% extends "package/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h2>{% trans "Example Form" %}</h2>
      
      <p>This form adds a website to the &ldquo;Sites using this package&rdquo; list.</p>
    
      <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
          {{ form|crispy }}

          <div class="form_block">        
            <input class="btn btn-default" type="submit" name="add" value="{% trans "Add new example" %}">
          </div>            
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_body %}
<script>
    $("#id_title").focus();
</script>
{% endblock %}

app/templates/package/ajax_package_list.html
{% load i18n %}
<div id="target">
    <h2>{% if packages|length %}{% trans "Packages" %}{% else %}{% trans "No packages found" %}{% endif %}</h2>
    {% if packages|length %}
        <p class="editable-cell">{% trans "Click a package to add it to the grid." %}</p>      
    {% endif %}
    {% for package in packages %}
        {% include "package/includes/_package_no_link.html" %}
    {% endfor %}
    <script type="text/javascript">
       
        {% for package in packages %}
            {% if package.slug not in packages_already_added_list %}
                $('#package-{{ package.id }}').mouseover(function() {
                    $('#package-{{ package.id }}').addClass("clickable");
                });
                $('#package-{{ package.id }}').mouseout(function() {
                    $('#package-{{ package.id }}').removeClass("clickable");
                });
                $('#package-{{ package.id }}').click(function() {
                
                    $('#package-field').attr("value", {{ package.id }});
                    $("form#grid-package-form").submit();
                });
            {% endif %}
        {% endfor %}

    </script>    
</div>

app/templates/package/base.html
{% extends "base.html" %}

app/templates/package/documentation_form.html
{% extends "package/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "package documentation form" %}{% endblock %}

{% block body %}

    <h2><a href="{% url 'home' %}">{% trans "home" %}</a> / <a href="{% url 'packages' %}">{% trans "packages" %}</a> / {{ action|title }} {% trans "package" %}</h2>

    <p id="package-form-message"></p>    
    <form action="{{ request.path }}" method="post" id="package-form">
        {{ form.errors }}
        {% csrf_token %}
        <fieldset>
            {{ form|crispy }}
        </fieldset>
        
        <input class="btn btn-default" type="submit" name="add" value="{{ action }} {% trans "Submit" %}">
    </form>

{% endblock %}

{% block extra_body %}
{% if not package.documentation_url.strip %}
<script type="text/javascript">
    $(function() {
        var url = "https://readthedocs.org/api/v1/build/{{ package.slug }}/?format=jsonp";
        $.ajax({
          url: url,
          dataType: 'jsonp',
          success:function(data){
              if (data.objects.length > 0){
                  var href = "https://readthedocs.org/projects/{{ package.slug }}";
                  $("#id_documentation_url").val(href);
              };
          }
        });
    });
</script>
{% endif %}

{% endblock %}

app/templates/package/edit_example.html
{% extends "package/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Edit package example" %}{% endblock %}

{% block body %}

    <h2>{% trans "Edit package example" %}</h2>
    
    <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form|crispy }}
            <div class="form_block">
                <input class="btn btn-default" type="submit" name="edit" value="{% trans "Edit" %}">            
                <a href="{% url 'package' package.slug %}">{% trans "cancel" %}</a>     
            </div>
        </fieldset>

    </form>

{% endblock %}


{% block extra_body %}
<script>
    $("#id_title").focus();
</script>
{% endblock %}

app/templates/package/images_form.html
{% extends "package/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{{ action|title }} {% trans "package" %}{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{{ STATIC_URL }}css/edit_form.css?deployment={{ DEPLOYMENT_DATETIME }}" type="text/css"/>
  {{ block.super }}
{% endblock %}

{% block body %}
    <h2>{{ package.name }}'s images</h2>

    <p id="package-form-message">
        We do not have image cropping tool yet. Suggested ratio for images is 16:9 (for example: 640×360, 1024×576, 1280×720, <b>1920x1080</b>)<br>
        Images with different ratio are scaled with <a href="https://www.w3schools.com/cssref/css3_pr_background-size.asp">cover property</a>. First image is used on main page.
    </p>
    <form action="{{ request.path }}" method="post" enctype="multipart/form-data" id="package-form">
        {% csrf_token %}
        {{ formset.management_form }}
        <div id="img-entries">
            {% for form in formset %}
                <div class="img-form" style="float: left; margin: 10px;">
                    <span class="rm-btn te-entry icon-close" title="Delete"></span>
                    {% if not form.errors %}
                        <img src="{{ form.img.value.url }}" style="width:16vw; height: 9vw; object-fit: cover;" />
                    {% endif %}
                    <div style="display: {% if form.errors %}block{% else %}none{% endif %}">
                        {{ form }}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div id="img-forms" style="clear: both;">

        </div>

        <div>
                <div id="formset-add-new-form-btn" class="m-btn m-btn--small">Add New Image</div>
        </div>
        <input class="m-btn" type="submit" name="add" value="Upload images and save changes">

    </form>

    <div id="empty-form" style="display:none;">
        <div class="img-form">
            {{ formset.empty_form }}
            <span class="rm-btn te-form icon-close"></span>
        </div>
    </div>

{% endblock %}

{% block extra_body %}
<script src="{{ STATIC_URL }}js/urlify.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/package_form.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function(){

        var rmEntry = function(event) {
            var imgForm = $(event.target).closest('.img-form');
            imgForm.find('input[type=checkbox]').prop('checked', true);
            imgForm.hide();
        };

        var rmForm = function(event) {
            var total_forms = $('#id_form-TOTAL_FORMS');
            var form_idx = total_forms.val();
            total_forms.val(parseInt(form_idx) - 1);

            $(event.target).closest('.img-form').remove();
        };

        $('.rm-btn.te-entry').click(rmEntry);
        $('.rm-btn.te-form').click(rmForm);

        $('#formset-add-new-form-btn').click(function (event) {
            var total_forms = $('#id_form-TOTAL_FORMS');
            var form_idx = total_forms.val();
            total_forms.val(parseInt(form_idx) + 1);

            var new_form = $($('#empty-form').html().replace(/__prefix__/g, form_idx));
            $('#img-forms').append(new_form);
            new_form.find('.rm-btn.te-form').click(rmForm);
        });
    });

</script>

{% endblock %}

app/templates/package/package_archive.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Packages" %}{% endblock %}

{% block body %}
<div class="row">
  <div class="col-xs-12">
    <h2>{% trans "Latest 50 packages added" %}</h2>
    {% if request.user.is_authenticated %}
        {% if profile.can_add_package %}
        <p><a class="btn  btn-default" href="{% url 'add_package' %}">{% trans "Add a new package!" %}</a></p>
        {% endif %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="list-group">
        {% for package in latest %}
            {% include "package/includes/_package.html"%}
        {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/package/package_grid.html
{% extends "base.html" %}

{% load i18n %}
{% load package_tags %}

{% block head_title %}List of all projects in {{ FRAMEWORK_NAME }} ecosystem{% endblock %}

{% block body %}
<div class="col-lg-12 m-projects-grid">
    {% for category in categories %}
        <div class="m-projects-grid__category">
            <h2 class="m-projects-grid__category-title">{{ category.title_plural }}</h2>
            <span class="m-projects-grid__category-counter">{{ category.count }}</span>

            <p class="m-projects-grid__category-description">{{ category.description }}</p>

            {% for package in category.packages %}
                {% project_tile package 'gallery'%}
            {% endfor %}
        </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/package/package_list.html
{% extends "base.html" %}

{% load i18n %}
{% load package_tags %}

{% block head_title %}{% trans "django reusable apps, sites and tools directory" %}{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
     {% for category in categories %}
        <h2><a href="{% url 'category' category.slug %}">{{ category.title_plural }}</a> ({{ category.count }})</h2>
        <p>{{ category.description }}</p>
        <table class="table">
          <thead>
            <tr>
                <th>{% trans "# Using This" %}</th>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Description" %}</th>
                <th>{% trans "Commits" %}</th>
                <th><span class="glyphicon glyphicon-star"></span></th>
                <th><span class="glyphicon glyphicon-random"></th>
            </tr>
          </thead>
          <tbody>
            {% for package in category.packages %}
              <tr>
                <td>
                  {% usage_button %}
                  <span class="usage-count">{{ package.usage_count }}</span>
                </td>
                <td><a href="{% url 'package' package.slug %}">{{ package.name }}</a></td>
                <td>{{ package.description }}</td>
                <td><img src="https://chart.googleapis.com/chart?cht=bvg&chs=105x20&chd=t:{{package|commits_over_52}}&chco=666666&chbh=1,1,1&chds=0,20" /></td>
                <td>{{ package.repo_watchers|default:"n/a" }}</td>
                <td>{{ package.repo_forks|default:"n/a" }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <p>
          <a href="{% url 'category' category.slug %}">
            {% trans "more " %}{{ category.title_plural|lower }}...
          </a>
        </p>
     {% endfor %}

{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    $(function() {
        $('input#id_q_p').click(function() {
            $("input#id_q_p").val('');
        });
    });

    $('#id_q_p').autocomplete({
      source: '{% url 'search_packages_autocomplete' %}',
      minLength: 1,
      open: function(event, ui) {
        ac_top = $('.ui-autocomplete').css('top');
        $('.ui-autocomplete').css({'width': '250px', 'top': ac_top + 10 });
      }
    });

</script>
{% endblock %}

app/templates/package/python3_list.html
{% extends "base.html" %}

{% load cache %}
{% load i18n %}
{% load package_tags %}
{% load pagination_tags %}
{% load sorting_tags %}

{% block head_title %}Python 3{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2><a href="{% url 'home' %}">{% trans "home" %}</a> / Python 3 ( {{ packages.count }} )</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      {% autosort packages %}
      {% autopaginate packages %}
      {% paginate %}
      <table class="table">
        <thead>
          <tr>
            <th>{% trans "Development Status" %}</th>
            <th>{% anchor title "Name" %}</th>
            <th>{% trans "Commits" %}</th>
            <th>{% trans "Version" %}</th>
            <th>{% anchor repo_watchers "Stars" %}</th>
            <th>{% anchor repo_forks "Forks" %}</th>
          </tr>
        </thead>

        <tbody>
        {% for package in packages %}
          <tr>
            <td>{{ package.last_released.pretty_status }}</td>
            <td><a href="{% url 'package' package.slug %}">{{ package.name }}</a></td>
            <td><img class="package-githubcommits" src="https://chart.googleapis.com/chart?cht=bvg&chs=105x20&chd=t:{{package.commits_over_52}}&chco=666666&chbh=1,1,1&chds=0,20" /></td>
            <td>{{ package.pypi_version }}</td>
            <td>{{ package.repo_watchers }}</td>
            <td>{{ package.repo_forks }}</td>
          </tr>
        {% endfor %}
        </tbody>
     </table>
     {% paginate %}

{% endblock %}